services:
  mysql:
    image: mariadb:11
    container_name: labs-mysql
    restart: unless-stopped
    ports:
      - '13306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${MYSQL_DB}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  mysql_data:
